### ISSUE TITLE
Add docker image for armv7 platform

### ISSUE THREAD

**Issue by noisymime** [ep1cman/unifi-protect-backup#103]
Similar to #45 , would it be possible to add an image tag for ARM v 7 (`linux/arm/v7`)? This would then support Raspberry Pi 1 and 2. 

I know these devices are fairly long in the tooth, but I'm currently running this on a Raspberry Pi 2 using the pip install and everything seems to work just fine. Would be great to have the docker image though.

**Comment by ep1cman** [comment]
Im afraid the upstream base image this container is based on has dropped support for Arm v7. For this reason I am unable to provide an arm v7 container at this time
