### ISSUE TITLE
Use latest rclone

### ISSUE THREAD

**Issue by advil0** [ep1cman/unifi-protect-backup#105]
Is it possible that the Dockerfile could be updated so that Rclone is the latest version available?  It's missing quite a few backends (notably the one I want to use ProtonDrive) that have been added.

**Comment by ep1cman** [comment]
The `latest` docker container should have rclone 1.64 which is the version proton drive was added in. It will be part of the next release too.

I had to move to the `edge` release of alpine to get a new enough version of rclone which I am not too sure on. If it causes problems I will roll back.

**Comment by advil0** [comment]
Thanks for getting this updated!  I want to warn anyone who comes upon this attempting to use Proton Drive, it appears as if they've suspended my Proton account due to this application, I'm guessing this kinda thing is against ToS.
