### ISSUE TITLE
Websocket not re-established if Unifi Protect restarts

### ISSUE THREAD

**Issue by ep1cman** [ep1cman/unifi-protect-backup#12]
* Unifi Protect Backup version: 0.3.0

### Description

Currently if UniFi Protect stops for any reason (e.g. a nightly update) the application does not realise the connection is a dead and never reconnects.

**Comment by Sticklyman1936** [comment]
I've tried to address this here: https://github.com/ep1cman/unifi-protect-backup/pull/13

Happy to hear your thoughts. I'm not overly happy with the solution to be frank, but it might work as a stopgap.

**Comment by ep1cman** [comment]
I agree its not an idea solution, but in my experience its tricky to know when a websocket has disconnected quickly, and pyunifiprotect doesn't really leave us a lot of options with how it handles managing its internal state. I suspect this will be "good enough". Thanks again for the patch :)
