### ISSUE TITLE
No module found

### ISSUE THREAD

**Issue by rcraig114** [ep1cman/unifi-protect-backup#123]
I noticed backups weren't appearing in onedrive the other day. Once I logged into my Ubuntu machine running the script, I am seeing "no module found." Any ideas?

Traceback (most recent call last):
  File "/home/unifi-protect-backup/.local/bin/unifi-protect-backup", line 5, in <module>
    from unifi_protect_backup.cli import main
ModuleNotFoundError: No module named 'unifi_protect_backup'

**Comment by johnraz** [comment]
Multiple things can cause this type of error.

- Did you upgrade Python to a new version?
- Did you make change to your PATH / PYTHONPATH?

Try `pip freeze |grep unifi` see if the package is still there.
Try reinstalling the with `pip install unifi-protect-backup` maybe?

It's hard to diagnose really but I feel like a reinstall would make it work.

**Comment by ep1cman** [comment]
Closing due to lack of response.
