### ISSUE TITLE
--min-age or any other filter options in RCLONE_PURGE_ARGS crushes deleting of old events

### ISSUE THREAD

**Issue by akinfold** [ep1cman/unifi-protect-backup#132]
* Unifi Protect Backup version: v0.10.5
* Unifi Protect version: 2.11.21
* Operating System: Synology OS
* Are you using a docker container or native?: docker

### Description

I was trying to configure unifi-protect-backup to upload only events younger then 1 day and delete files older then 30 days. To do so I passed following env variables to unifi-protect-backup:
```
...
-e RCLONE_RETENTION='1d' \
-e RCLONE_PURGE_ARGS='--min-age=30d' \
...
```
As a result unifi-protect-backup upload all events younger then 1 day, but delete nothing from remote. Container logs tells that there was error running comand ```rclone delete -vv "crypt:/nvr/2024-02-15/2024-02-15T07-39-20 motion.mp4" --min-age=30d```:
```
	2024/03/16 23:15:46 can't limit to single files when using filters: crypt:/nvr/2024-02-15/2024-02-15T07-39-20 motion.mp4
```
I think it wold be more clear to add to documentation that RCLONE_PURGE_ARGS and --rclone-purge-args must not contain any filters available for ```rclone delete``` command.

**Comment by ep1cman** [comment]
You should not be configuring rclone purging and retention directly like this.

Instead please use the configuration settings provided by this tool. It handles what files to upload and when to delete them
