### ISSUE TITLE
no --version option

### ISSUE THREAD

**Issue by timotab** [ep1cman/unifi-protect-backup#15]
Unifi Protect Backup version: 0.3.1
Python version: 3.9.10
Operating System: Raspbian GNU/Linux 10 (buster)

### Description

Tried to get version of the software, expected it to show a version. I had to use pip to figure out version

### What I Did

```
(unifi-backup) thunt@raspberrypi:~ $ unifi-protect-backup --version
Usage: unifi-protect-backup [OPTIONS]
Try 'unifi-protect-backup --help' for help.

Error: No such option: --version (Possible options: --retention, --verbose)
```

**Comment by ep1cman** [comment]
Added in v0.4.0, thanks for pointing this out!
