### ISSUE TITLE
Time lapse?

### ISSUE THREAD

**Issue by feenx** [ep1cman/unifi-protect-backup#155]
### Description

Any ability to back up time lapses? I believe UniProtect is generating time-lapse videos as well.

**Comment by ep1cman** [comment]
I don't believe timeplase events are a thing? 

How would it work to backup time lapses?

**Comment by feenx** [comment]
Yeah, apologies, seems the UniFi Protect UI fooled me by playing the videos quickly until I choose a specific point to watch at normal speed.
