### ISSUE TITLE
PyPI publish for 0.11.0 failed

### ISSUE THREAD

**Issue by fletchowns** [ep1cman/unifi-protect-backup#159]
* Unifi Protect Backup version: N/A
* Unifi Protect version: N/A
* Python version: N/A
* Operating System: N/A
* Are you using a docker container or native?: N/A

### Description

Looks like 0.11.0 failed to publish to PyPI: https://github.com/ep1cman/unifi-protect-backup/actions/runs/9424717076/job/25965412481
```
 Uploading unifi_protect_backup-0.11.0-py3-none-any.whl
25l
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/60.4 kB • --:-- • ?
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/60.4 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB • 00:00 • 75.1 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB • 00:00 • 75.1 MB/s
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         User 'ep1cman' does not have a verified primary email address. Please  
         add a verified primary email before attempting to upload to PyPI. See  
         https://pypi.org/help/#verified-email for more information.        
```

As a result, the latest version currently available on PyPI at this time is 0.10.7: https://pypi.org/project/unifi-protect-backup/#history

Thanks for the great package!

**Comment by ep1cman** [comment]
Hi, sorry for taking so long to get back to you. This is caused by the fact that this release was made of a custom fork of pyunifiprotect that is not available on PyPI. Once the necessary functionality is included in uiprotect the next release will be on PyPi

**Comment by fletchowns** [comment]
No problem! I know you have a life and obligations outside of all the time you volunteer to this project, and I appreciate the work you put into this for everybody to benefit from. Thank you!!
