### ISSUE TITLE
S3 integration

### ISSUE THREAD

**Issue by zarmstrong** [ep1cman/unifi-protect-backup#2]
Native support to upload clips to s3 would be nice. The Boto3 lib should make this easy. 

https://aws.amazon.com/sdk-for-python/

**Comment by ep1cman** [comment]
This tool uses `rclone` in the background to do all its uploading. It seems like `rclone` already supports S3: https://rclone.org/s3/

You should just be able to configure a rclone remote for S3 and use that as the destination for `unifi-protect-backup`, but I am not familiar with S3. Happy to help debug if you can share logs.

**Comment by zarmstrong** [comment]
Oh nice! I don't know rclone, so that's definitely nice to know. I'll try messing around with it soon, prob won't have time until March

**Comment by ep1cman** [comment]
Feel free to re-open if you face issues once you do test it out
