### ISSUE TITLE
rclone: too many non-flag arguments

### ISSUE THREAD

**Issue by ep1cman** [ep1cman/unifi-protect-backup#22]
### Discussed in https://github.com/ep1cman/unifi-protect-backup/discussions/21

<div type='discussions-op-text'>

<sup>Originally posted by **Amphiboly** March  7, 2022</sup>
It appears that poorly formatted file names are being passed to rclone. I get the message:
Command rcat needs 1 arguments maximum: you provided 2 non flag arguments: ["'remote:Unifi\\Wanderer\\2022-03-07\\2022-03-07T03-20-06" "motion.mp4'"]
when my camera name has no spaces, and
Command rcat needs 1 arguments maximum: you provided 4 non flag arguments: ["'remote:Unifi\\Mud" "Room" "Door\\2022-03-07\\2022-03-07T03-20-05" "motion.mp4'"]
when it has two spaces. So even if I were to rename the camera "Front Door" to "FrontDoor" it looks like there will still be a problem because of the "motion.mp4" addition.

This is on Windows 11 with the current versions of all involved packages (Python 3.10.2, unifi-protect-backup 0.5.0, pyunifiprotect 3.2.1, ffprobe 0.5, rclone 1.57.0).

unifi-protect generates test data per the readme, and rclone rcat can put files into the target directory.

What should I look at next?

-- 
rik</div>

**Comment by ep1cman** [comment]
I also have cameras with spaces in their names. It looks like this issue comes from a difference in how this script runs on windows vs linux/mac. I hadn't tested it on windows. I will look into fixing this tonight and push a new release ASAP

**Comment by Amphiboly** [comment]
Indeed, all is now well. Thank you.
