### ISSUE TITLE
Destination file and path names, timezone

### ISSUE THREAD

**Issue by ep1cman** [ep1cman/unifi-protect-backup#27]
### Discussed in https://github.com/ep1cman/unifi-protect-backup/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **Amphiboly** March  9, 2022</sup>
All is working well, thank you. This is an enhancement request.

I see that the destination file and path names are based on the UTC date expansion of the event start time. The result for me (in EST5EDT) is that many events are placed in a directory with the next day's date (relative to the local time).

![image](https://user-images.githubusercontent.com/10307457/157556673-b50b50af-2497-497c-968e-1b5213b619e6.png)

Is there a way to use the local time to fashion the file and directory names?

-- 
Rik</div>

**Comment by ep1cman** [comment]
Are you able to test the current "main" branch to see if this fixes the issue for you before I do a release

**Comment by Amphiboly** [comment]
Everything looks good with the new main branch.

**Comment by johnwarne-gt** [comment]
Hey there, has this been integrated into the latest Docker image? I'm still seeing UTC datetimes in the files (and their resulting directories).

**Comment by johnwarne** [comment]
Hey there, has this been integrated into the latest Docker image? I'm still seeing UTC datetimes in the files (and their resulting directories) when using the latest Docker image.

**Comment by Amphiboly** [comment]
I thought that it had been fixed, but I still see UTC datetimes as well. There was an interim fix that I tested and thought it gave correct results, but after updating to from 0.52 to 0.53, the interim fix must have disappeared.

**Comment by ep1cman** [comment]
https://github.com/ep1cman/unifi-protect-backup/commit/0a4a2401bef3d9016322c8541c9bd23805a5368c
Should have fixed this and is included in v0.5.3 (which as per: https://github.com/ep1cman/unifi-protect-backup/pkgs/container/unifi-protect-backup you can see is also the `latest` container image) 

I will look into this now and see if I can reproduce the issue.

**Comment by ep1cman** [comment]
Ok I have gone and actually changed the timezone on my UDM, and it seems the previous fixed didn't fix it at all. Its strange that it worked for you @Amphiboly.

I am now working on properly fixing it, expect a new v0.5.4 release in the next few hours that resolves this

**Comment by ep1cman** [comment]
Can you both try the 'dev' branch/'dev' container tag to check if it is indeed fixed for you too

**Comment by johnwarne** [comment]
Just pulled the dev container and the change seemed to work for me! Datetimes in the file names are now in my timezone. Woot!

**Comment by Amphiboly** [comment]
Working for me as well on W11.
![image](https://user-images.githubusercontent.com/10307457/159076119-e12a0a24-03ba-4844-9ded-cc2c6f8b1f3b.png)

**Comment by ep1cman** [comment]
Ok hopefully this is resolved in v0.6.0, if it appears again please re-open
