### ISSUE TITLE
Feature Request: Option to skip previous recordings

### ISSUE THREAD

**Issue by ouaibe** [ep1cman/unifi-protect-backup#61]
### Enhancement Request

It would be great to have an option to avoid re-uploading past videos, so that when working from a new setup and/or a DB refresh, users do not have to forcibly upload GBs of data (without knowing how much data the days of video represents) and can assume a future-recording only approach.

This could take the form of an environment variable like the others that would make the script only react to new recording events and not try to match previous missing ones.

**Comment by natehudson** [comment]
+1
I just upgraded to the latest version and it is now uploading ~8000 videos to my remote storage. ;-)

Thanks for all the hard work on this tool!

**Comment by ep1cman** [comment]
implemented in 0.9.0
