### ISSUE TITLE
new to python

### ISSUE THREAD

**Issue by tikesavage** [ep1cman/unifi-protect-backup#66]
* Unifi Protect Backup version: CB   UDM PRO
* Unifi Protect version:  CB   UDM PRO
* Python version: 3
* Operating System: Ubuntu Server 
* Are you using a docker container or native?:

### Description

issue with getting Python code to run.

### What I Did
 followed instructions  for rclone with g drive. and installed python, pip and ffprobe.  now need to run the code. 
 
 
```
~/.local/lib/python3.10/site-packages/unifi_protect_backup$ python3 unifi_protect_backup.py

error:

Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 16, in <module>
    from unifi_protect_backup import EventListener, MissingEventChecker, Purge, VideoDownloader, VideoUploader
  File "/home/username/.local/lib/python3.10/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 16, in <module>
    from unifi_protect_backup import EventListener, MissingEventChecker, Purge, VideoDownloader, VideoUploader
ImportError: cannot import name 'EventListener' from partially initialized module 'unifi_protect_backup' (most likely due to a circular import) (/home/username/.local/lib/python3.10/site-packages/unifi_protect_backup/unifi_protect_backup.py)

```

**Comment by ep1cman** [comment]
You shouldn't run the python file directly like that. If you have done a `pip install` you should instead just run the command `unifi-protect-backup`

**Comment by tikesavage** [comment]
no luck either, tried that first.  
~/.local/lib/python3.10/site-packages/unifi_protect_backup$ unifi-protect-backup
unifi-protect-backup: command not found

**Comment by ep1cman** [comment]
Have you tried logging out and back in?

https://askubuntu.com/a/1384895

**Comment by tikesavage** [comment]
yes ^^
PIP 'worked'  but i reinstalled with pip3  and that resolved it for me.

my follow up is can you provide some sanitized exampled of  using calling the module?

visual learner really helps

**Comment by ep1cman** [comment]
Do you mean the command line tool? The module itself is not intended to be used directly. I would suggest checking out pyunifiprotect if that's what you want.

As for how to use the tool, if you run `unifi-protect-backup --help` it will explain all the options and which ones are required. It can also be found in the readme.
