### ISSUE TITLE
Add support for line crossing events

### ISSUE THREAD

**Issue by ep1cman** [ep1cman/unifi-protect-backup#69]
Unifi protect at some point added "Line crossing" events that are separate from motion or smart detect events. This tool should handle those too.

**Comment by ep1cman** [comment]
It seems new detection types have been added too: alarms, packages

**Comment by adidalal** [comment]
First off, amazing package, thanks very much! Just set this up recently for an offsite backup.

I'm happy to attempt a PR for this - wanted to check here first if my understanding is correct.

New Types to add: `"package", "animal", "smartDetectLine"`. There's a whole bunch of sound alarm types as well now too, but I'm not sure how much specificity is useful.

- The new types already exist in [`pyunifiprotect`](https://github.com/AngellusMortis/pyunifiprotect/blob/5ab14e0f00cc892914313712ad26da4f1f7cf800/pyunifiprotect/data/types.py#L233)
- Add them to [DETECTION_TYPES](https://github.com/ep1cman/unifi-protect-backup/blob/e65d8dde6c1399bd87f293a676bad69409f87662/unifi_protect_backup/cli.py#L13)
- Add a new set of conditionals to [`event_listener._websocket_callback`](https://github.com/ep1cman/unifi-protect-backup/blob/e65d8dde6c1399bd87f293a676bad69409f87662/unifi_protect_backup/event_listener.py#L49) - depending on your thoughts about alarm types, I may refactor a teensy bit here.

**Comment by ep1cman** [comment]
That sounds about right, and would definitely appreciate a PR!

I can see the audio events being useful, they're just not something I've tested yet within unifi protect. I'm not sure if they are sent in the same structure so it would need some investigation.

That function has a lot of conditions in it, I'm open to suggestions on how to improve it if you have any. It was done this way to try and keep the filtering of events readable and easy to reason about. Pattern matching might be a potential alternative approach but I worry with that many conditions it might become less readable.
