### ISSUE TITLE
running out of memory

### ISSUE THREAD

**Issue by split-brain-83** [ep1cman/unifi-protect-backup#75]
Hi, I've upgraded from 0.7.x to 0.8.8 and now unifi-protect-backup is eating all the memory of the NAS I'm running it. 
It has around 450MB of reserverd and 1300MB of virtual memory. Also there is a constant large read load on the disk and the cpu load is also high at times. 

Should I downgrade to eliminate the ram (and swap) filling problem?

free -h
              total        used        free      shared  buff/cache   available
Mem:           908M        697M         84M        2.6M        126M         39M
Swap:          2.5G        1.0G        1.5G

ps aux 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     20508 26.9 47.6 1428404 443192 ?      Dl   16:59   5:43 /var/packages/python310/target/bin/python3.10 /var/packages/python310/target/bin/unifi-protect-backup --no-verify-ssl --address 192.168.2.1 --port 443 --username backup --password xxx --detection-types motion --retention 90d --download-buffer-size 64MiB --rclone-destination nas:/volume1/backup/protect/

**Comment by ep1cman** [comment]
Any chance you could share a log so I can see what it's doing that's could be taking up so much memory.

I suspect the high disk usage is due to swap.

**Comment by split-brain-83** [comment]
[unifi_protect.log](https://github.com/ep1cman/unifi-protect-backup/files/10423996/unifi_protect.log)

**Comment by ep1cman** [comment]
Looking at that log you have a backlog of 43579 not downloaded events. The event object is a fairly large JSON object so I wouldn't be surprised if that's what's causes the memory usage, which should get better once its worked its way through the backlog. 1GB of RAM really isn't a lot to work with.

There is a feature request open at the moment (#61) for adding a way to disable this. Another way to attempt to fix this would be wrapping the list of missing events with something that chunks them up, which should be doable because the API has an option to limit the number of events returns.

**Comment by split-brain-83** [comment]
Yes I understand, that there are so many events to download and the system has very limited  ram. unifi-protect-backup is doing what it can, but eventually it hangs and no further events are backed up.
I'm thinking about deploying unifi-protect-backup to some more competent machine, because this is killing that poor NAS :)

**Comment by ep1cman** [comment]
I would highly recommend that. You could try to move it back over once that initial backlog is dealt with, once its in stable state, it shouldnt be so demanding

**Comment by ep1cman** [comment]
I was jsut running the tool through a profiler to find way to minimise memory usage (already found one major way to save memory) and saw this in my logs

```
One drive root 'unifi_test/Hallway (Downstairs)/2023-01-12': Target remote doesn't support streaming uploads, creating temporary local FS to spool file
```
looks like for some remotes rclone does actually write to disk, which is less than ideal. I will look into if this can be done with a ramdisk somehow.
