### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ep1cman** [ep1cman/unifi-protect-backup#77]
### Discussed in https://github.com/ep1cman/unifi-protect-backup/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **Swallowtail23** December  8, 2022</sup>
The buffer size causing unifi-protect-backup to hang for me on the 342MB video got me thinking... No matter the limit, at some point someone is going to have a Unifi video that is too big...

Feature request:
As this is ideally run "headless", configure options for SMTP alert notification, or some other way for push notifications in event of a failed download/upload, or perhaps a "daily digest" style end of day container/app health update/stats summary to ensure ongoing successful function / recovery from failure. </div>

https://github.com/caronc/apprise < Implement using this

**Comment by ep1cman** [comment]
implemented in 0.9.0

**Comment by Swallowtail23** [comment]
With this in docker command: 
`  -e APPRISE_NOTIFIERS='pover://<user key in here>/<api token in here>'`
...I get errors and the container won't run...

What is the format it is looking for? I also tried `  -e APPRISE_NOTIFIERS='ERROR,WARNING=pover://<user key in here>/<api token in here>'`

**Comment by Swallowtail23** [comment]
Ignore that, it needed an @ in the middle not the slash... I think it's going now :)
